<div>
    @auth
        @role('admin')
            @livewire('navigation.admin-menu')
        @else
            @role('instructor')
                @livewire('navigation.instructor-menu')
            @else
                @role('student')
                    @livewire('navigation.student-menu')
                @endrole
            @endrole
        @endrole
    @else
        @livewire('navigation.guest-menu')
    @endauth
</div>
